[E 250730 12:02:09 smartConnect:221] Error occurred while making a POST request to https://apiconnect.angelone.in/rest/secure/angelbroking/order/v1/getLtpData. Headers: {'Content-type': 'application/json', 'X-ClientLocalIP': '127.0.0.1', 'X-ClientPublicIP': '106.193.147.98', 'X-MACAddress': 'f8:a2:d6:02:c2:bd', 'Accept': 'application/json', 'X-PrivateKey': 'uQBIgMGv', 'X-UserType': 'USER', 'X-SourceID': 'WEB', 'Authorization': 'Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VybmFtZSI6IlM2OTI5NDgiLCJyb2xlcyI6MCwidXNlcnR5cGUiOiJVU0VSIiwidG9rZW4iOiJleUpoYkdjaU9pSlNVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKMWMyVnlYM1I1Y0dVaU9pSmpiR2xsYm5RaUxDSjBiMnRsYmw5MGVYQmxJam9pZEhKaFpHVmZZV05qWlhOelgzUnZhMlZ1SWl3aVoyMWZhV1FpT2pRc0luTnZkWEpqWlNJNklqTWlMQ0prWlhacFkyVmZhV1FpT2lJek0yUTBNek0yTVMxbFlUWmtMVE5sTTJVdFlUUmpZaTB5WXpkaU9UY3hOMlZqWVdJaUxDSnJhV1FpT2lKMGNtRmtaVjlyWlhsZmRqSWlMQ0p2Ylc1bGJXRnVZV2RsY21sa0lqbzBMQ0p3Y205a2RXTjBjeUk2ZXlKa1pXMWhkQ0k2ZXlKemRHRjBkWE1pT2lKaFkzUnBkbVVpZlN3aWJXWWlPbnNpYzNSaGRIVnpJam9pWVdOMGFYWmxJbjBzSW01aWRVeGxibVJwYm1jaU9uc2ljM1JoZEhWeklqb2lZV04wYVhabEluMTlMQ0pwYzNNaU9pSjBjbUZrWlY5c2IyZHBibDl6WlhKMmFXTmxJaXdpYzNWaUlqb2lVelk1TWprME9DSXNJbVY0Y0NJNk1UYzFNemt5TlRrek1Td2libUptSWpveE56VXpPRE01TXpVeExDSnBZWFFpT2pFM05UTTRNemt6TlRFc0ltcDBhU0k2SWpSaE9HSmxZamhpTFRNd00yTXROR0k1WWkxaFpEWm1MV1EzTVRKbFl6aGtNVFV4TWlJc0lsUnZhMlZ1SWpvaUluMC5Xa056RnRyZlJEeWk3ZmFWaXdtNGRraHQyQTMzX0Y5SC12aERtSFV0bGNLQXN2SzF2X3k0ekJsbDJrd3V2QkZRc2t6LW52c3gzQ1Q0NDBhN0FiTkxobm1MbWFMWVh4dzdKdjVQX05sWjhIRGhmTThobWtHbURpMDhXOHFHOGd3VWRGblBZWVNIUTJUekEwZnRSMExjTDVYTDNxYlJfTmx4RUtPOU5GckRoSmciLCJBUEktS0VZIjoidVFCSWdNR3YiLCJpYXQiOjE3NTM4Mzk1MzUsImV4cCI6MTc1MzkyNTkzMX0.189eq6y_ug8yATh6AGZ4keyAt_jVAeeeBtZlrhj2K2veeuCRKjPxnz5ik2ReEt_j9N-2dKBdL0EY-KVD1Yg29A'}, Request: {'exchange': 'NFO', 'tradingsymbol': 'NIFTY31JUL2524800PE', 'symboltoken': '55792'}, Response: HTTPSConnectionPool(host='apiconnect.angelone.in', port=443): Read timed out. (read timeout=7)
[E 250730 12:02:10 smartConnect:221] Error occurred while making a POST request to https://apiconnect.angelone.in/rest/secure/angelbroking/order/v1/getLtpData. Headers: {'Content-type': 'application/json', 'X-ClientLocalIP': '127.0.0.1', 'X-ClientPublicIP': '106.193.147.98', 'X-MACAddress': 'f8:a2:d6:02:c2:bd', 'Accept': 'application/json', 'X-PrivateKey': 'uQBIgMGv', 'X-UserType': 'USER', 'X-SourceID': 'WEB', 'Authorization': 'Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VybmFtZSI6IlM2OTI5NDgiLCJyb2xlcyI6MCwidXNlcnR5cGUiOiJVU0VSIiwidG9rZW4iOiJleUpoYkdjaU9pSlNVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKMWMyVnlYM1I1Y0dVaU9pSmpiR2xsYm5RaUxDSjBiMnRsYmw5MGVYQmxJam9pZEhKaFpHVmZZV05qWlhOelgzUnZhMlZ1SWl3aVoyMWZhV1FpT2pRc0luTnZkWEpqWlNJNklqTWlMQ0prWlhacFkyVmZhV1FpT2lJek0yUTBNek0yTVMxbFlUWmtMVE5sTTJVdFlUUmpZaTB5WXpkaU9UY3hOMlZqWVdJaUxDSnJhV1FpT2lKMGNtRmtaVjlyWlhsZmRqSWlMQ0p2Ylc1bGJXRnVZV2RsY21sa0lqbzBMQ0p3Y205a2RXTjBjeUk2ZXlKa1pXMWhkQ0k2ZXlKemRHRjBkWE1pT2lKaFkzUnBkbVVpZlN3aWJXWWlPbnNpYzNSaGRIVnpJam9pWVdOMGFYWmxJbjBzSW01aWRVeGxibVJwYm1jaU9uc2ljM1JoZEhWeklqb2lZV04wYVhabEluMTlMQ0pwYzNNaU9pSjBjbUZrWlY5c2IyZHBibDl6WlhKMmFXTmxJaXdpYzNWaUlqb2lVelk1TWprME9DSXNJbVY0Y0NJNk1UYzFNemt5TlRrek1Td2libUptSWpveE56VXpPRE01TXpVeExDSnBZWFFpT2pFM05UTTRNemt6TlRFc0ltcDBhU0k2SWpSaE9HSmxZamhpTFRNd00yTXROR0k1WWkxaFpEWm1MV1EzTVRKbFl6aGtNVFV4TWlJc0lsUnZhMlZ1SWpvaUluMC5Xa056RnRyZlJEeWk3ZmFWaXdtNGRraHQyQTMzX0Y5SC12aERtSFV0bGNLQXN2SzF2X3k0ekJsbDJrd3V2QkZRc2t6LW52c3gzQ1Q0NDBhN0FiTkxobm1MbWFMWVh4dzdKdjVQX05sWjhIRGhmTThobWtHbURpMDhXOHFHOGd3VWRGblBZWVNIUTJUekEwZnRSMExjTDVYTDNxYlJfTmx4RUtPOU5GckRoSmciLCJBUEktS0VZIjoidVFCSWdNR3YiLCJpYXQiOjE3NTM4Mzk1MzUsImV4cCI6MTc1MzkyNTkzMX0.189eq6y_ug8yATh6AGZ4keyAt_jVAeeeBtZlrhj2K2veeuCRKjPxnz5ik2ReEt_j9N-2dKBdL0EY-KVD1Yg29A'}, Request: {'exchange': 'NFO', 'tradingsymbol': 'NIFTY31JUL2524800PE', 'symboltoken': '55792'}, Response: HTTPSConnectionPool(host='apiconnect.angelone.in', port=443): Max retries exceeded with url: /rest/secure/angelbroking/order/v1/getLtpData (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020C6708CE10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
[E 250730 12:02:11 smartConnect:221] Error occurred while making a POST request to https://apiconnect.angelone.in/rest/secure/angelbroking/order/v1/getLtpData. Headers: {'Content-type': 'application/json', 'X-ClientLocalIP': '127.0.0.1', 'X-ClientPublicIP': '106.193.147.98', 'X-MACAddress': 'f8:a2:d6:02:c2:bd', 'Accept': 'application/json', 'X-PrivateKey': 'uQBIgMGv', 'X-UserType': 'USER', 'X-SourceID': 'WEB', 'Authorization': 'Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VybmFtZSI6IlM2OTI5NDgiLCJyb2xlcyI6MCwidXNlcnR5cGUiOiJVU0VSIiwidG9rZW4iOiJleUpoYkdjaU9pSlNVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKMWMyVnlYM1I1Y0dVaU9pSmpiR2xsYm5RaUxDSjBiMnRsYmw5MGVYQmxJam9pZEhKaFpHVmZZV05qWlhOelgzUnZhMlZ1SWl3aVoyMWZhV1FpT2pRc0luTnZkWEpqWlNJNklqTWlMQ0prWlhacFkyVmZhV1FpT2lJek0yUTBNek0yTVMxbFlUWmtMVE5sTTJVdFlUUmpZaTB5WXpkaU9UY3hOMlZqWVdJaUxDSnJhV1FpT2lKMGNtRmtaVjlyWlhsZmRqSWlMQ0p2Ylc1bGJXRnVZV2RsY21sa0lqbzBMQ0p3Y205a2RXTjBjeUk2ZXlKa1pXMWhkQ0k2ZXlKemRHRjBkWE1pT2lKaFkzUnBkbVVpZlN3aWJXWWlPbnNpYzNSaGRIVnpJam9pWVdOMGFYWmxJbjBzSW01aWRVeGxibVJwYm1jaU9uc2ljM1JoZEhWeklqb2lZV04wYVhabEluMTlMQ0pwYzNNaU9pSjBjbUZrWlY5c2IyZHBibDl6WlhKMmFXTmxJaXdpYzNWaUlqb2lVelk1TWprME9DSXNJbVY0Y0NJNk1UYzFNemt5TlRrek1Td2libUptSWpveE56VXpPRE01TXpVeExDSnBZWFFpT2pFM05UTTRNemt6TlRFc0ltcDBhU0k2SWpSaE9HSmxZamhpTFRNd00yTXROR0k1WWkxaFpEWm1MV1EzTVRKbFl6aGtNVFV4TWlJc0lsUnZhMlZ1SWpvaUluMC5Xa056RnRyZlJEeWk3ZmFWaXdtNGRraHQyQTMzX0Y5SC12aERtSFV0bGNLQXN2SzF2X3k0ekJsbDJrd3V2QkZRc2t6LW52c3gzQ1Q0NDBhN0FiTkxobm1MbWFMWVh4dzdKdjVQX05sWjhIRGhmTThobWtHbURpMDhXOHFHOGd3VWRGblBZWVNIUTJUekEwZnRSMExjTDVYTDNxYlJfTmx4RUtPOU5GckRoSmciLCJBUEktS0VZIjoidVFCSWdNR3YiLCJpYXQiOjE3NTM4Mzk1MzUsImV4cCI6MTc1MzkyNTkzMX0.189eq6y_ug8yATh6AGZ4keyAt_jVAeeeBtZlrhj2K2veeuCRKjPxnz5ik2ReEt_j9N-2dKBdL0EY-KVD1Yg29A'}, Request: {'exchange': 'NFO', 'tradingsymbol': 'NIFTY31JUL2524800PE', 'symboltoken': '55792'}, Response: HTTPSConnectionPool(host='apiconnect.angelone.in', port=443): Max retries exceeded with url: /rest/secure/angelbroking/order/v1/getLtpData (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020C6708D090>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
